name: A-Car_everyday  #yml文件名字
# JD自动开卡
on:
 schedule:
   - cron: '0 2,3 * * *'#定时，和北京时间差8小时。这里其实就是10点11点各运行一次
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: 'Set up Python'
       uses: actions/setup-python@v1
       with:
         python-version: 3.7
       
     - name: '配置调用'#显示的名字，随意
       run: pip install -r ./Xxx/C.TXT#调用的支持库
       
     - name: '自动运行' #随意
       run: workflows/jd_OpenCard.py#你的py代码在github的路径
       env:
           Card_telegram: ${{ secrets.Card_telegram }}#py通知参数
           Car_cookies: ${{ secrets.Car_cookies }}  #你的py代码中ck
